@webapiHostAddress = https://localhost:32783
@employeeId = 1

POST {{webapiHostAddress}}/employeesecurity/{{employeeId}}/permissions
Content-Type: application/json

{
  "permissionTypeId": 1
}

###

POST {{webapiHostAddress}}/employeesecurity/{{employeeId}}/permissions
Content-Type: application/json

{
  "permissionTypeId": 4
}

###

# El empleado no existe
POST {{webapiHostAddress}}/employeesecurity/25/permissions
Content-Type: application/json

{
  "permissionTypeId": 4
}

###

# El permiso no existe
POST {{webapiHostAddress}}/employeesecurity/1/permissions
Content-Type: application/json

{
  "permissionTypeId": 8
}

###